plugins {
	id 'java'
	id 'maven-publish'
	id 'eclipse'
	id 'net.neoforged.gradle.userdev' version '7.0.165'
}

group = "net.foxmcloud.draconicadditions"
base.archivesName = "Draconic-Additions"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//Add generated resources to main resources.
sourceSets.main.resources.srcDirs += "src/main/generated"

def signProps = [:]

mod_version = "${mod_version}.${buildNo}"
version = "${mc_version}-${mod_version}"
println "Starting build of ${base.archivesName.get()}, Version: ${mod_version}"
println "Using NeoForge: ${neo_version}, for Minecraft: ${mc_version},"

minecraft {
	accessTransformers.file file("src/main/resources/META-INF/accesstransformer.cfg")
}

runs {
	client {
		workingDirectory file('run')
	}
	server {
		workingDirectory file('run')
	}
	data {
		workingDirectory file('run')
		arguments.addAll '--mod', 'draconicadditions', '--all', '--output', file("src/main/generated").absolutePath, '--existing', file("src/main/resources").absolutePath, '--existing', file("../Draconic-Evolution/src/main/resources").absolutePath
	}
}

repositories {
	maven { url = "https://chickenbones.net/maven/" }
	maven { url = "https://maven.blamejared.com/" }
	maven { url = "https://maven.theillusivec4.top/" }
}

dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"
	implementation "com.brandon3055.brandonscore:BrandonsCore:${mc_version}-${bcore_version}"
	implementation "io.codechicken:CodeChickenLib:${mc_version}-${ccl_version}"

	implementation("mezz.jei:jei-${mc_version}-neoforge:${jei_version}") {
        transitive false
    }
	implementation("io.codechicken:EnderStorage:${mc_version}-${ender_storage_version}") {
        transitive false
    }

	implementation("top.theillusivec4.curios:curios-neoforge:${curios_version}") {
        transitive false
    }

	implementation("com.brandon3055.draconicevolution:Draconic-Evolution:${mc_version}-${de_version}")
}

processResources {
	inputs.property 'mc_version', mc_version
	inputs.property 'mod_version', mod_version
	inputs.property 'bcore_version', bcore_version
	inputs.property 'de_version', de_version

	filesMatching('META-INF/neoforge.mods.toml') {
		expand 'file': ['jarVersion': mod_version],
			'mc_version': mc_version,
			'neo_version': neo_version,
			'lang_version': neo_version.split('\\.')[0],
			'ccl_version': "[${ccl_version.replace('.+', '')},${ccl_version_max})",
			'bcore_version': bcore_version,
			'curios_version': mc_version + "-" + curios_version,
			'de_version': de_version
	}
}

jar {
	archiveClassifier = ''
	from file("LICENSE")
	manifest {
		attributes 'Specification-Title': base.archivesName.get()
		attributes 'Specification-Vendor': 'FoxMcloud5655'
		attributes 'Specification-Version': "1"
		attributes 'Implementation-Title': base.archivesName.get()
		attributes 'Implementation-Vendor': 'FoxMcloud5655'
		attributes 'Implementation-Version': version
		attributes 'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
	}
}

task srcJar(type: Jar) {
	build.dependsOn it
	from sourceSets.main.allSource
	archiveClassifier = 'sources'
	from file("LICENSE")
}

/**
 * Polls the 'compile' configuration for a dependency with the given module name
 * and resolves, and returns its version. E.g: '1.2.+' will resolve to '1.2.3.4'
 *
 * @param module The module to search for.
 * @param chop If the string should be chopped on the last '-' in its string.
 * @param configuration The name of the configuration to search.
 * @param errorMissing If an error should be thrown if it can't be found.
 * @return The version string, '0' if 'errorMissing' is false and nothing was found.
 */
def resolve(module, chop = true, configuration = 'compile', errorMissing = true) {
	//Copy and lenient resolve the configuration, Forge cant be resolved at this time so lenient is required.
	def filtered = configurations.getByName(configuration).copy().incoming.artifactView({ it.lenient = true }).artifacts
			.findAll { it.id.componentIdentifier.module == module }
			.collect { it.id.componentIdentifier.version }
	if (filtered.size() > 1) {
		println "WARNING: Found ${filtered.size()} Dependencies with ModuleName '${module}' in configuration '${configuration.name}'"
	}
	if (errorMissing && filtered.isEmpty()) {
		throw new RuntimeException("Failed resolve dependency version for '${module}'")
	}
	if (filtered.isEmpty()) return "0"
	def version = filtered.first() as String
	if (chop) {
		def idx = version.lastIndexOf('-')
		return version.substring(idx + 1)
	}
	return version
}
